<?
require('conn.php');
$sql0="drop table 교수시간표";
$sql1="drop table 수강";
$sql2="drop table 교과목";
$sql3="drop table 시간";
$sql4="drop table 요일";
$sql5="drop table 강의실";
$sql6="drop table 건물";
$sql7="drop table 학생";
$sql8="drop table 조교";
$sql9="drop table 교수";
$sql10="drop table 관리자";
$sql11="drop table 학과";
$result0=oci_parse($conn, $sql0);
$result1=oci_parse($conn, $sql1);
$result2=oci_parse($conn, $sql2);
$result3=oci_parse($conn, $sql3);
$result4=oci_parse($conn, $sql4);
$result5=oci_parse($conn, $sql5);
$result6=oci_parse($conn, $sql6);
$result7=oci_parse($conn, $sql7);
$result8=oci_parse($conn, $sql8);
$result9=oci_parse($conn, $sql9);
$result10=oci_parse($conn, $sql10);
$result11=oci_parse($conn, $sql11);
$re0=oci_execute($result0);
$re1=oci_execute($result1);
$re2=oci_execute($result2);
$re3=oci_execute($result3);
$re4=oci_execute($result4);
$re5=oci_execute($result5);
$re6=oci_execute($result6);
$re7=oci_execute($result7);
$re8=oci_execute($result8);
$re9=oci_execute($result9);
$re10=oci_execute($result10);
$re11=oci_execute($result11);
oci_close($conn);
echo(" <meta http-equiv='Refresh' content='0; URL=index.html'>");
?>